kind: Service
apiVersion: v1
metadata:
  name: eventstore-service
spec:
  clusterIP: None
  selector:
    name: eventstore-node
  ports:
  - name: 'internal-http'
    protocol: TCP
    port: 2113
    targetPort: 2113
  - name: 'external-http'
    protocol: TCP
    port: 2114
    targetPort: 2114
  - name: 'external-tcp'
    protocol: TCP
    port: 1113
    targetPort: 1113
  - name: 'internal-tcp'
    protocol: TCP
    port: 1112
    targetPort: 1112
